name: palimpsest
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.2
  - aiosignal=1.4.0
  - alembic=1.16.5
  - annotated-types=0.7.0
  - async-timeout=5.0.1
  - attr=2.5.2
  - attrs=25.4.0
  - aws-c-auth=0.8.6
  - aws-c-cal=0.8.7
  - aws-c-common=0.12.0
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.4
  - aws-c-http=0.9.4
  - aws-c-io=0.17.0
  - aws-c-mqtt=0.12.2
  - aws-c-s3=0.7.13
  - aws-c-sdkutils=0.2.3
  - aws-checksums=0.2.3
  - aws-crt-cpp=0.31.0
  - aws-sdk-cpp=1.11.510
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.4.26
  - cairo=1.18.4
  - catalogue=2.0.10
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - click=8.3.0
  - cloudpathlib=0.23.0
  - cloudpickle=3.1.2
  - cmudict=1.0.32
  - colorama=0.4.6
  - confection=0.1.5
  - coverage=7.12.0
  - cpython=3.10.19
  - cuda-crt-tools=12.9.86
  - cuda-cudart=12.9.79
  - cuda-cudart_linux-64=12.9.79
  - cuda-cuobjdump=12.9.82
  - cuda-cupti=12.9.79
  - cuda-nvcc-tools=12.9.86
  - cuda-nvdisasm=12.9.88
  - cuda-nvrtc=12.9.86
  - cuda-nvtx=12.9.79
  - cuda-nvvm-tools=12.9.86
  - cuda-version=12.9
  - cudnn=9.10.2.21
  - cusparselt=0.7.0.0
  - cymem=2.0.13
  - cython-blis=1.3.3
  - datasets=2.14.4
  - dill=0.3.7
  - exceptiongroup=1.3.1
  - filelock=3.20.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.14.1
  - frozenlist=1.7.0
  - fsspec=2025.10.0
  - ftfy=6.3.1
  - gflags=2.2.2
  - git=2.49.0
  - git-filter-repo=2.38.0
  - git-lfs=3.7.0
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - greenlet=3.2.2
  - h2=4.3.0
  - harfbuzz=11.2.1
  - hf-xet=1.1.5
  - hpack=4.1.0
  - huggingface_hub=0.36.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - importlib-metadata=8.6.1
  - importlib-resources=6.5.2
  - importlib_resources=6.5.2
  - iniconfig=2.3.0
  - jinja2=3.1.6
  - joblib=1.5.2
  - keyutils=1.6.3
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20240722.0
  - libarrow=19.0.1
  - libarrow-acero=19.0.1
  - libarrow-dataset=19.0.1
  - libarrow-substrait=19.0.1
  - libblas=3.11.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.77
  - libcblas=3.11.0
  - libcrc32c=1.1.2
  - libcublas=12.9.1.4
  - libcudnn=9.10.2.21
  - libcudnn-dev=9.10.2.21
  - libcudss0=0.4.0.2
  - libcufft=11.4.1.4
  - libcufile=1.14.1.1
  - libcurand=10.3.10.19
  - libcurl=8.14.1
  - libcusolver=11.7.5.82
  - libcusparse=12.5.10.65
  - libdeflate=1.25
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libglib=2.84.3
  - libgomp=15.1.0
  - libgoogle-cloud=2.36.0
  - libgoogle-cloud-storage=2.36.0
  - libgrpc=1.67.1
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - libllvm20=20.1.8
  - liblzma=5.8.1
  - libmagma=2.8.0
  - libnghttp2=1.64.0
  - libnl=3.11.0
  - libnsl=2.0.1
  - libnvjitlink=12.9.86
  - libopenblas=0.3.30
  - libopentelemetry-cpp=1.18.0
  - libopentelemetry-cpp-headers=1.18.0
  - libparquet=19.0.1
  - libpng=1.6.50
  - libprotobuf=5.28.3
  - libre2-11=2024.07.02
  - libsqlite=3.49.2
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libsystemd0=258.2
  - libthrift=0.21.0
  - libtiff=4.7.1
  - libtorch=2.6.0
  - libudev1=258.2
  - libutf8proc=2.10.0
  - libuuid=2.38.1
  - libuv=1.51.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - make=4.3
  - mako=1.3.10
  - markdown-it-py=4.0.0
  - markupsafe=3.0.2
  - mdurl=0.1.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - msgpack-python=1.1.0
  - multidict=6.6.3
  - multiprocess=0.70.15
  - murmurhash=1.0.15
  - nccl=2.28.9.1
  - ncurses=6.5
  - networkx=3.4.2
  - nlohmann_json=3.12.0
  - nodeenv=1.9.1
  - nodejs=22.13.0
  - nomkl=1.0
  - numpy=2.2.6
  - openjpeg=2.5.4
  - openssl=3.5.0
  - optree=0.18.0
  - orc=2.1.1
  - packaging=25.0
  - pandas=2.3.3
  - pandoc=2.19.2
  - pcre2=10.45
  - perl=5.32.1
  - pillow=12.0.0
  - pip=25.1.1
  - pixman=0.46.4
  - pluggy=1.6.0
  - preshed=3.0.12
  - prometheus-cpp=1.3.0
  - propcache=0.3.1
  - pthread-stubs=0.4
  - pyarrow=19.0.1
  - pyarrow-core=19.0.1
  - pybind11=3.0.1
  - pybind11-global=3.0.1
  - pycparser=2.22
  - pydantic=2.12.5
  - pydantic-core=2.41.5
  - pygments=2.19.2
  - pynvim=0.5.2
  - pypandoc=1.16.2
  - pyphen=0.17.2
  - pyright=1.1.407
  - pysocks=1.7.1
  - pytest=9.0.1
  - pytest-cov=7.0.0
  - pytest-mock=3.15.1
  - python=3.10.17
  - python-dateutil=2.9.0.post0
  - python-gil=3.10.19
  - python-tzdata=2025.2
  - python-xxhash=3.6.0
  - python_abi=3.10
  - pytorch=2.6.0
  - pytz=2025.2
  - pyyaml=6.0.2
  - rdma-core=60.0
  - re2=2024.07.02
  - readline=8.2
  - regex=2025.11.3
  - requests=2.32.5
  - rich=14.2.0
  - ruff=0.14.6
  - s2n=1.5.14
  - safetensors=0.7.0
  - scikit-learn=1.7.2
  - scipy=1.15.2
  - sentence-transformers=5.1.2
  - setuptools=80.1.0
  - shellingham=1.5.4
  - six=1.17.0
  - sleef=3.9.0
  - smart-open=7.5.0
  - smart_open=7.5.0
  - snappy=1.2.2
  - spacy=3.8.11
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.5
  - sqlalchemy=2.0.43
  - srsly=2.5.2
  - sympy=1.14.0
  - tectonic=0.15.0
  - textstat=0.7.7
  - thinc=8.3.10
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tokenizers=0.21.2
  - tomli=2.2.1
  - tqdm=4.67.1
  - transformers=4.55.4
  - triton=3.2.0
  - typer=0.20.0
  - typer-slim=0.20.0
  - typer-slim-standard=0.20.0
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025b
  - ujson=5.11.0
  - urllib3=2.5.0
  - vale=3.13.0
  - wasabi=1.1.3
  - wcwidth=0.2.13
  - weasel=0.4.3
  - wheel=0.45.1
  - wrapt=2.0.1
  - write-good=1.0.8
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xxhash=0.8.3
  - yaml=0.2.5
  - yarl=1.22.0
  - zipp=3.21.0
  - zlib=1.3.1
  - zlib-ng=2.3.1
  - zstandard=0.25.0
  - zstd=1.5.7

prefix: "/home/soffiafdz/.local/share/micromamba/envs/palimpsest"
